// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Values from google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForGoogleServices',
    appId: '1:937435569832:android:a1b2c3d4e5f6g7h8',
    messagingSenderId: '937435569832',
    projectId: 'vibtrix',
    storageBucket: 'vibtrix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForGoogleServices',
    appId: '1:937435569832:ios:a1b2c3d4e5f6g7h8',
    messagingSenderId: '937435569832',
    projectId: 'vibtrix',
    storageBucket: 'vibtrix.appspot.com',
    iosBundleId: 'com.rektech.vibtrix',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDummyKeyForGoogleServices',
    appId: '1:937435569832:web:a1b2c3d4e5f6g7h8',
    messagingSenderId: '937435569832',
    projectId: 'vibtrix',
    storageBucket: 'vibtrix.appspot.com',
    authDomain: 'vibtrix.firebaseapp.com',
  );
}
